name: Build Devbox

on: [push, pull_request]
jobs:
    build:
        name: "Build Devbox"
        runs-on: ubuntu-latest
        container:
            image: archlinux
        steps:
            - name: Installing zig
              run: |
                  ZIG_VERSION=0.10.0

                  wget -nv https://ziglang.org/download/$ZIG_VERSION/zig-linux-x86_64-$ZIG_VERSION.tar.xz
                  tar -xvf zig-linux-x86_64-$ZIG_VERSION.tar.xz
                  sudo mv ./zig-linux-x86_64-$ZIG_VERSION/zig /usr/bin
                  sudo mv ./zig-linux-x86_64-$ZIG_VERSION/lib /usr/lib/zig

            - name: Get required pacman pkgs
              run: |
                  sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
                  pacman --noconfirm --noprogressbar -Syyu
                  pacman --noconfirm --noprogressbar -Sy go make

            - name: Checkout Devbox
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Build Devbox zig_static
              run: |
                  make clean
                  make

            - name: Build Devbox musl_static
              run: |
                  make clean
                  make musl_static

            - name: Build Devbox
              run: |
                  make clean
                  make build

            - name: Formatting Check
              run: |
                  make check

            - name: Tests
              run: |
                  make test
